from .common import db, Field
from pydal.validators import *
import datetime

db.define_table('company',
                Field('IAN_FULL_NAME'),
                Field('FIN_TYPE'),
                Field('IM_NUMIDENT', type='integer', length=8),
                Field('IAN_RO_SERIA'),
                Field('IAN_RO_CODE'),
                Field('IAN_RO_DT',type='datetime'),
                Field('DIC_NAME'),
                Field('F_ADR'),
                Field('IA_PHONE_CODE'),
                Field('IA_PHONE'),
                Field('IA_EMAIL'),
                Field('IND_OBL'),
                Field('K_NAME'),
                Field('abbreviation'),
                Field('position'),
                Field('update_date', type='datetime'),
                Field('changes'))
db.define_table('company_user',
                Field('site_user','reference auth_user'),
                Field('company_id','reference company'))
db.define_table('ir4_description',
                Field('name', type='string'),
                Field('p_id', type='integer'),
                Field('ekp', type='string'),
                Field('h015', type='string'),
                Field('k030', type='string'),
                Field('z220', type='string'))
db.define_table('fr1_description',
                Field('ekp', type='string'),
                Field('f061', type='string'),
                Field('h001', type='string'))
db.define_table('vid_strah',
                Field('name'),
                Field('type', type='string'),
                Field('nfp_id', type='string'),
                Field('nbu_id', type='string'),
                Field('iar_kod', type='string'),
                Field('key1', type='string'),
                Field('key2', type='string'),
                Field('key3', type='string'))
db.define_table('errors',
                Field('kod', type='integer'),
                Field('ua', type='string'),
                Field('en', type='string'),
                Field('ru', type='string'))
db.define_table('fr1',
                Field('ekp', type='string'),
                Field('t100_1', type='integer'),
                Field('t100_2', type='integer'),
                Field('f061', type='string'),
                Field('h001', type='string'),
                Field('quarter', type='integer'),
                Field('year', type='integer'),
                Field('company_id', 'reference company'),
                Field('upload_date', type='datetime', default = datetime.date.today()))
db.define_table('type',
                Field('ekp', type='string'),
                Field('h011', 'reference vid_strah'),
                Field('h015', type='string'),
                Field('k030', type='string'),
                Field('z220', type='string'),
                Field('t100', type='integer'),
                Field('quarter', type='integer'),
                Field('year', type='integer'),
                Field('company_id', 'reference company'),
                Field('upload_date', type='datetime', default = datetime.date.today()))
db.define_table('type_orig',
                Field('ekp', type='string'),
                Field('h011', 'reference vid_strah'),
                Field('h015', type='string'),
                Field('k030', type='string'),
                Field('z220', type='string'),
                Field('t100', type='integer'),
                Field('quarter', type='integer'),
                Field('year', type='integer'),
                Field('company_id', 'reference company'),
                Field('upload_date', type='datetime', default = datetime.date.today()))
db.define_table('payout',
                Field('insurance_type', 'reference vid_strah'),
                Field('contract_num', type='string'),
                Field('case_num', type='string'),
                Field('insurance_case_date', type='datetime'),
                Field('statement_date', type='datetime'),
                Field('requirement_date', type='datetime'),
                Field('insurance_act_date', type='datetime'),
                Field('insurance_payment_date', type='datetime'),
                Field('insurance_payment_size', type='integer'),
                Field('settlement_costs', type='integer'),
                Field('company_id', 'reference company'),
                Field('upload_date', type='datetime', default = datetime.date.today()))
db.define_table('rezerv',
                Field('insurance_type', 'reference vid_strah'),
                Field('contract_num', type='string'),
                Field('case_num', type='string'),
                Field('insurance_case_date', type='datetime'),
                Field('statement_date', type='datetime'),
                Field('requirement_date', type='datetime'),
                Field('insurance_act_date', type='datetime'),
                Field('insurance_payment_date', type='datetime'),
                Field('insurance_payment_size', type='integer'),
                Field('reserve_size', type='integer'),
                Field('insert_date', type='datetime'),
                Field('company_id', 'reference company'),
                Field('upload_date', type='datetime', default = datetime.date.today()))
db.commit()